### ISSUE TITLE
Updated Oct. 26 RCASD Notice

### ISSUE THREAD

**Issue by Woliver01** [NeighborhoodInfoDC/DHCD#60]
For Nov Catalog

**Comment by Woliver01** [comment]
Hi @ptatian, I have a couple questions. For one, the changes I made to the format program aren't showing up in the desktop repository of GitHub. Also, I'm getting this error when I run the format program: ERROR: Write access to member DHCD.FORMATS.CATALOG is denied.

**Comment by ptatian** [comment]
Hi @Woliver01. For the first question, it appears you are editing the program on L:, not on D:. Please copy the program you created on L: to D: and then you will be able to commit those changes. Please let me know when you have done that, as I will have to reset the L: drive folder to sync with the remote master. 

Testing programs that create formats is a little different than other programs because you can't update the format catalog on L: when you run the program on your desktop.  Once you've committed your changes, would you please do a pull request on this issue and then I can review your code and give you more guidance? Thanks!
