### ISSUE TITLE
DC Preservation Catalog July 2019 Update

### ISSUE THREAD

**Issue by mcohenui** [NeighborhoodInfoDC/DHCD#76]
_Note: If you have not previously done so, [clone the DHCD repo](https://help.github.com/desktop/guides/contributing-to-projects/cloning-a-repository-from-github-to-github-desktop/) to **D:\DCData\Libraries** before proceeding._
- [ ] [Create new branch](https://help.github.com/desktop/guides/contributing-to-projects/creating-a-branch-for-your-work/) **update-#**_n_ in GitHub Desktop for work on this issue (where _n_=issue number). 
- [ ] [Update DHCD RCASD notices](https://urbanorg.app.box.com/notes/100799532204)
- [ ] [Request review and finalize programs](https://urbanorg.app.box.com/notes/295752223069)

**Comment by ptatian** [comment]
@Woliver01 @mcohenui I've updated the programs and [instructions](https://urbanorg.app.box.com/notes/100799532204) to address the new RCASD file format. Please be sure to fetch and pull the latest changes into your local DHCD repo before creating a new branch for this update. As I mentioned, the files are now PDFs so there is an extra step involved to process them. 

I created a new **Prog\RCASD\Rcasd_2019.sas** program and added a few of the weekly files to it so that I could test it. You should download and add the remaining files for 2019 (Jan 21 - Jun 7). You will likely encounter some unrecognized notice types because, in addition to changing the format, DHCD also changed some of the notice labels. For instance, they added "single family dwelling," "2-4 units," and "5+ units" to the beginning of some of the notice types. I decided to just make these new notices, rather than combining them with the existing notices that were more generic. 

I know you've dealt with adding notice before, but I added info to the instructions on this process. Let me know if you have questions. Thanks!

**Comment by mcohenui** [comment]
@Woliver01 If this month and the May updates have been merged, please close.
